Form section
maury18/My-Portfolio pull request #3
Opened 2022-04-26 22:21 UTC by maury18

# added the form section for contact me:
- CSS for the form.
- Form validation.
- Added the "Formspree".
- more description added for the "Readme" file
- cleared from linter errors

2022-04-26 22:29 UTC, youmari requested changes
Hi, @maury18 @mikemtzp , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

✔️ NO linters error 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 22:29 UTC, youmari commented on index.html
> +                <button type="submit" class="submit">
- [ ] nice implementing button style effect on hover but you should also implement it when the button is pressed so please try to do so

2022-04-26 22:29 UTC, youmari commented on index.html
> +        <img src="/img/last-black-rectangle.png" alt="" class="form-black-rectangle">
your images not working maybe they work on your machine but on all the machines to fix this please try to add a dot before the slash like this  `src="./img/form(the rest here)"`

2022-04-27 00:18 UTC, BenMukebo approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi Team**, 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- The form is submitted successfully with valid input values. :heavy_check_mark:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ OPTIONAL] This is a group project. Please let's include all the authors in the README file.
- [ OPTIONAL]  Please let's make sure that contribution to a group project is distributed equally among the members( commit messages should be fairly equal).

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 00:18 UTC, BenMukebo commented on css/styles.css
> +}
- [OPTIONAL ] The Button interactions such as hover, active (when it's pressed), disabled and enable (default state) are styled as shown in the Figma template. Please use the some CSS properties from the Figma design look ⬇️ 

![buttongood](https://user-images.githubusercontent.com/79058364/165333032-7d562e97-53c3-4614-a452-1f680d6fcf41.png)

2022-04-27 00:26 UTC, BenMukebo commented on css/styles.css
> +  border: none;
- [OPTIONAL ] Kindly give 12px of padding to all placeholder or input value as you can see on the Figma design

Your design    |        Figma
---------:|:------------
![figmabad](https://user-images.githubusercontent.com/79058364/165413967-af46fde3-ba68-4327-95fd-93b83bb93fc3.png) | ![figmagood](https://user-images.githubusercontent.com/79058364/165414006-3f3100be-4317-4265-8153-c90b31a0a966.png)

2022-04-27 03:01 UTC, merged