Java script section
maury18/My-Portfolio pull request #9
Opened 2022-05-12 04:43 UTC by maury18

In this branch I added javascript to add some interactions for the menu button, you can move to the section that you want to see by clicking on its link.

- Function to open the menu button
-  Function to close the menu button
- Changed all the background images and instead, I added one that has all the background icons (couldn´t set it in a better position).
- The media queries for it´s resolution are 375px (mobile screen) and 1024px (desktop screen).
- 
![image](https://user-images.githubusercontent.com/73630406/167993660-91add9b6-bdc3-412e-8720-854448a5fe3c.png)

2022-05-12 05:21 UTC, Ismailco requested changes
### Hi @maury18,

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-12 05:21 UTC, Ismailco commented on README.md
>  # My-Portfolio
- [ ] This is the first project in which you should set up both [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linters in the project repository, you can use [this config files instead](https://github.com/microverseinc/linters-config/tree/master/html-css-js)

2022-05-12 05:21 UTC, Ismailco commented on scripts/scripts.js
> +    console.log(icon);
- [ ] Try to not commit ```console.log``` to your repo. It’s ugly, it kills performance and it can make confidential data visible to anyone using the browser tools to look at your website.

2022-05-12 05:21 UTC, Ismailco commented on scripts/scripts.js
> +        nav.classList.toggle('nav-active');
- [ ] When the user clicks (or taps) the close (X) button, the mobile menu does not disappear, please consider hiding the menu instead of sliding it to the right

![Screenshot_20220512_055429](https://user-images.githubusercontent.com/25227022/167995156-01e1e086-d051-4c55-814e-a2639c95360e.png)![Screenshot_20220512_055913](https://user-images.githubusercontent.com/25227022/167995229-04af06a9-16b0-42bb-ac8c-bb01de962c57.png)

2022-05-12 05:21 UTC, Ismailco commented on css/styles.css
> +.close-menu {
- [ ] The mobile menu needs to follow the design from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colors, images, margins), you can start by adding some blur to the background

2022-05-12 05:21 UTC, Ismailco commented on css/styles.css
> +.close-menu {
- [ ] The menu does not take all the space of the page, please consider using 100% ```width``` and ```height``` 

![Screenshot_20220512_061115](https://user-images.githubusercontent.com/25227022/167996465-b8a78ded-1a65-4f99-96fc-f05f2b88259e.png)

2022-05-12 05:21 UTC, Ismailco commented on css/styles.css
> +  font-weight: 600;
- [ ] Please consider using the right ```font-weight``` and ```font-family``` for the close button, so your design is as close to the Figma design as possible

2022-05-12 05:21 UTC, Ismailco commented on css/styles.css
> +.close-menu {
- [ ] You can add some margin to the menu links so your design is as close to the provided design as possible

2022-05-14 23:23 UTC, smunozmo requested changes
Hi @maury18, 👋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ 

You have submitted a project, that is not passing all linters checks.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-14 23:44 UTC, MrRamoun approved these changes
# 🟢 Project Approved! 🏆

## Hi @maury18 👋

Your project is complete! ✔️ 🏁

Finally, **you did it**! 🎉 👏. Your code was very professional 💯 and I can see you have a great chance to be a Great Software Engineer ⛑️.

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉. And Welcome to Microverse 👋.

> **Note:** You can now take a break even if short before you move on to the next project. Happy 😄 Coding 🖥️! and Have a nice day 🌞.

## Highlights 🌟

- ✔️ very very descriptive PR description
- ✔️ very descriptive PR title
- ✔️ descriptive commit messages
- ✔️ very good accessability
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️
- This is My **GitHub**: [![@mrramoun](https://img.shields.io/github/followers/MrRamoun?label=Ramoun&style=social)](https://github.com/mrramoun)
- This is My **Twitter**: [![@ramoun16](https://img.shields.io/twitter/follow/ramoun16?label=ramoun16&style=social)](https://twitter.com/ramoun16)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-15 02:50 UTC, merged

2022-05-16 18:30 UTC, prolajumokeoni reviewed
Hi @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._